language: cpp
compiler:
  - clang

sudo: false

addons:
    apt:
        packages:
        - cmake

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda config --add channels http://conda.binstar.org/omnia
<<<<<<< HEAD
  - conda create --yes -n py3 python=3 --file ci/requirements-conda.txt
  - source activate py3
  - $HOME/miniconda3/envs/py3/bin/pip install $PIP_ARGS nose-exclude
  - conda install --yes openmm=6.2 runipy
=======
  - conda install --yes openmm=6.3 runipy numpy cython pip nose swig
>>>>>>> 9899ea112ceac84e76945042658593195fb659b2

install:
  - export PATH=$HOME/miniconda3/bin:$PATH
  - mkdir build
  - cd build
  - cmake .. -DOPENMM_MAJOR_VERSION=6 -DOPENMM_MINOR_VERSION=3 -DCMAKE_INSTALL_PREFIX=$HOME/miniconda3/ -DOPENMM_DIR=$HOME/miniconda3/
  - make VERBOSE=1
  - make install
  - make PythonInstall

script:
  - make test
  - cd ../python
  - runipy water14.ipynb
  - mbpol_builder mbpol_config.ini example_run.py
  - python example_run.py && python -c "import os.path; import sys; sys.exit(not os.path.isfile('water14_cluster_trajectory.pdb'))"
  - cd tests
  - ./run_tests
